import Head from "next/head";
import { App, Button, Space } from "antd";

export default function Home() {
  const { message, modal, notification } = App.useApp();

  const showMessage = () => {
    message.success("Success!");
  };

  const showModal = () => {
    modal.warning({
      title: "This is a warning message",
      content: "some messages...some messages...",
    });
  };

  const showNotification = () => {
    notification.info({
      message: `Notification topLeft`,
      description: "Hello, Ant Design!!",
      placement: "topLeft",
    });
  };
  return (
    <div className="flex justify-center items-center h-full">
      <Head>
        <title>eCommerce Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Space>
        <Button type="primary" onClick={showMessage}>
          Open message
        </Button>
        <Button type="primary" onClick={showModal}>
          Open modal
        </Button>
        <Button type="primary" onClick={showNotification}>
          Open notification
        </Button>
      </Space>
    </div>
  );
}
