import Head from "next/head";
import { App, Button, Space, Typography } from "antd";
import Image from "next/image";
import CustomImage from "@/components/custom-image";
import { useRouter } from "next/router";

export default function Home() {
  const { message, modal, notification } = App.useApp();
  const router = useRouter();

  const showMessage = () => {
    message.success("Success!");
  };

  const showModal = () => {
    modal.warning({
      title: "This is a warning message",
      content: "some messages...some messages...",
    });
  };

  const showNotification = () => {
    notification.info({
      message: `Notification topLeft`,
      description: "Hello, Ant Design!!",
      placement: "topLeft",
    });
  };

  return (
    <>
      <Head>
        <title>eCommerce Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-full">
        <div className="text-xl text-center select-none uppercase mb-5 font-serif">
          Book at Ecommerce
        </div>
        <div className="flex flex-col gap-5">
          <CustomImage src={"/static/images/hero-1.jpg"} />
          <CustomImage src={"/static/images/hero-2.jpg"} />
          <div className="flex">
            <div className="flex-1">
              <CustomImage src={"/static/images/hero-sub-1.jpg"} />
            </div>
            <div className="flex-1">
              <CustomImage src={"/static/images/hero-sub-2.png"} />
            </div>
            <div className="flex-1">
              <CustomImage src={"/static/images/hero-sub-3.jpg"} />
            </div>
            <div className="flex-1">
              <CustomImage src={"/static/images/hero-sub-4.jpg"} />
            </div>
          </div>
        </div>
      </div>
      <div className="grid place-items-center">
        <Button
          type="primary"
          size="large"
          className="my-10"
          onClick={() => router.push("/book")}
        >
          Discover Book
        </Button>
      </div>
    </>
  );
}
